Proceso CONDICIONALUMNO
	Definir CONDICIONP Como Entero;
	Definir NOTA1, NOTA2, NOTA3, PROM Como Real;
	Escribir 'INGRESE LA CONDICION PARA LA PROMOCION';
	Leer CONDICIONP;
	Escribir 'INGRESE LAS NOTAS A EVALUAR LA PROMOCION';
	Leer NOTA1, NOTA2, NOTA3;
	PROM <- (NOTA1+NOTA2+NOTA3)/3;
	Si PROM>=CONDICIONP Entonces
		Escribir 'PROMOCIONA';
	SiNo
		Si PROM<CONDICIONP Entonces
			Escribir 'NO PROMOCIONA';
		FinSi
	FinSi
FinProceso
